# Generated by Django 5.1.3 on 2024-11-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_courses_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='students',
            name='department',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
